config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root to: "users#index", as: :authenticated_root
    end

    unauthenticated :user do
      root to: "devise/sessions#create", as: :unauthenticated_root
    end
  end

  resources :users do
    resources :posts do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end

  resources :posts, only: [:index]

end

app/models/ability.rb
class Ability
  include CanCan::Ability
end

# app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    if user.admin?
      # Admins can do anything
      can :manage, :all
    else
      # A logged-in user can manage their own resources
      can :manage, Post, user_id: user.id
      can :manage, Comment, user_id: user.id
      can :manage, Like, user_id: user.id

      # A user can view other users' posts, comments, and likes (read-only access)
      can :read, Post
      can :read, Comment
      can :read, Like

      # Users can like posts, even if they are not the owner
      can :create, Like

      # Custom rule: a user can only update or destroy their own comments
      can :update, Comment, user_id: user.id
      can :destroy, Comment, user_id: user.id

      # Example of a user can only delete their own likes
      can :destroy, Like, user_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  enum status: { published: 0, unlisted: 1, archived: 2 }
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :title, presence: true
  validates :content, presence: true
  validates :comments_counter, numericality: { only_integer: true }
  validates :likes, numericality: { only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable, :confirmable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :image, ImageUploader
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :bio, presence: true, length: {
    maximum: 1000,
    message: '%<count>s characters is the maximum allowed'
  }
  validates :password, presence: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:first_name, :last_name, :bio, :twitter, :email, :password, :password_confirmation, :image)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @user = User.includes(:posts).find(params[:user_id])
    @post = @user.posts.find(params[:post_id])
    @comment = @post.comments.new
  end

  def create
    @user = User.includes(:posts).find(params[:user_id])
    @post = @user.posts.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user

    if @comment.save
      @post.increment!(:comments_counter)
      redirect_to user_post_path(@user, @post), notice: 'Comment was successfully created'
    else
      render :new
    end
  end

  def destroy
    # You can implement destroy action if needed
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @user = User.includes(:posts).find(params[:user_id])
    @post = @user.posts.find(params[:post_id])

    if @post.likes.exists?(user_id: current_user.id)
      flash[:alert] = 'post already liked'
    else
      @like = @post.likes.create(user_id: current_user.id)
      @post.increment!(:likes)
      redirect_to user_post_path(@user.id, @post.id), notice: 'Like was successfully created'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    if params[:user_id]
      @user = User.includes(:posts).find(params[:user_id])
      @posts = @user.posts
    else
      @posts = Post.all.includes(:user)
    end
  end

  def show
    @user = User.includes(:posts).find(params[:user_id])
    @post = @user.posts.find(params[:id])
    @comments = @post.comments.all
    @like = @post.likes.new(user_id: current_user.id)
  end

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      current_user.increment!(:posts_counter)
      redirect_to user_posts_path, notice: 'Post was successfully created'
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    if @post.update(post_params)
      redirect_to user_posts_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    if @post.destroy
      redirect_to user_posts_path(@user), alert: 'Post successfully deleted'
    else
      redirect_to user_posts_path(@user), alert: 'Post could not be deleted'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = if params[:search].present?
               User.where('first_name ILIKE ? OR last_name ILIKE ?', "%#{params[:search]}%", "%#{params[:search]}%")
             else
               User.all
             end
  end

  def show
    @user = User.find_by(id: params[:id])
    if @user.nil?
      redirect_to users_path, alert: 'user not found'
    else
      @user_posts = @user.posts.includes(:user).limit(3)
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path, alert: 'User successfully deleted'
  end

  private

  def user_params
    params.require(:user).permit(:first_name, last_name, photo, bio, posts_counter, twitter, phone, email, password,
                                 image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<br />
<section class='d-flex justify-content-center'>
  <div class='card w-75 border-success'>
    <div class='card-header d-flex justify-content-center header'>
      <h2 class='text-success'>Log in</h2>
    </div>

    <div class='card-body'>
      <%= form_with(model: [@user, @post, @comment], local: true) do |form| %>
        <div class="form-group">
          <%= form.label :comment %>
          <br />
          <%= form.text_area :comment, class:'form-control post_content' %>
        </div>
  
        <div class='d-flex justify-content-center'>
          <%= form.submit "Add comment", class: 'btn btn-outline-primary' %>
        </div>
      <% end %>
    </div>
  </div>

</section>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>


    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>NkookiBlog</title>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class='container'>
      <% if user_signed_in? %>
        <%= render 'partials/header' %>
      <% end %>
      <%= yield %>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/partials/_header.html.erb
  <nav class="navbar navbar-expand-lg navbar-light bg-light"> 
    <%= link_to "NKOOKI BLOG", users_path %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto w-50 d-flex justify-content-around">
        <li class="nav-item">
          <%= link_to "Home", users_path %>
        </li>
        <li class="nav-item">
          <%= link_to 'Create', new_user_post_path(current_user) %>
        </li>  
        <li class="nav-item">          
          <%= link_to 'Posts', posts_path %>
        </li> 
        
      </ul>
      <%= button_to 'Log Out', destroy_user_session_path, method: :delete %> 
    </div>
  </nav>

app/views/partials/_post.html.erb
<ul class='d-flex justify-content-center'>
  <li class='w-75 p-1 bg-light rounded'>
    <h5 class='d-flex justify-content-center'>
    <%= post.title %>
    <br />
    By: (<%= post.user.first_name %> <%= post.user.last_name %>)
    </h5>
    
    <div>
      <% if post.content.present? && post.content.length > 5 %>
        <%= post.content.slice(0..5) %>...
        <%= link_to 'more', user_post_path(post.user.id, post) %>
      <% else %>
        <%= post.content %>
      <% end %>      
    </div>    
    
    <div class='d-flex justify-content-end'>
      status: <%= post.status %>
    </div>
    <div>
      Comments: <%= post.comments_counter %>
      Likes: <%= post.likes.count %>
    </div>  
  </li>
</ul>

app/views/partials/_user.html.erb
<section class='container'>
  <div class='d-flex user_profile_container'>
    <div class='d-flex justify-content-center align-items-center profile_image_container'> 
      <img src= '<%= user.photo %>' alt='profile pic' >
    </div>
    <div class='d-flex flex-column justify-content-center align-items-center w-100'>
      <div class='d-flex justify-content-between w-75'>
        <div class='w-50 d-flex justify-content-between'>
          <span><%= user.first_name %></span>
          <span><%= user.last_name %></span>
        </div>
        <%= link_to 'All posts', user_posts_path(user.id) %>

      </div>
      <div class='d-flex justify-content-end w-100'>
        <span class='edit_link'>
          <%= link_to 'Show', user_path(user.id) %>
        </span>
        <span class='edit_link'>
          <%= link_to 'Edit', edit_user_registration_path %>
        </span>
        <span>
          <%= link_to 'Delete', user_path(current_user), data: {
            turbo_method: :delete,
            turbo_confirm: 'Are you sure?'
          } %>
        </span>
      </div>
    </div>
  </div>
  <br />
  <div class='card-footer d-flex justify-content-between'>
    <div>
      Posts: <%= user.posts_counter %>
    </div>
    <div>
      Joined: <%= user.created_at.in_time_zone(Time.zone).strftime("%B %d, %Y %I:%M %p") %>
    </div>
  </div>
</section>
<br/>

app/views/posts/edit.html.erb
<br />
<section class='d-flex justify-content-center'>
  <div class='card w-75 border-success'>
    <div class='card-header d-flex justify-content-center header'>
      <h2 class='text-success'>Edit post</h2>
    </div>

    <div class='card-body'>
      <%= form_with(model: [@user, @post], url: user_post_path(@user, @post), method: :patch) do |form| %>
        <div class="form-group">
          <%= form.label :title %>
          <br />
          <%= form.text_field :title, required: true, class:'form-control' %>
        </div>
    
        <br />
        <div class="form-group">
          <%= form.label :content %>
          <br />
          <%= form.text_area :content, required: true, class:'form-control post_content' %>
        </div>

        <div class='d-flex justify-content-center'>
          <%= form.submit "Update post", class: 'btn btn-outline-primary' %>
        </div>
      <% end %>
    </div>

  </div>
</section>

app/views/posts/index.html.erb
<br />

<% @posts.each do |post| %>
  <div class='d-flex justify-content-center'>
  <div class='w-75 d-flex justify-content-end'>
     <div>
       <%= link_to 'edit', edit_user_post_path(post.user.id, post), class:'btn btn-outline-primary m-1' %>
     </div>
     <div>
       <%= link_to 'Delete', user_post_path(post.user.id, post.id), data: {
          turbo_method: :delete,
          turbo_confirm: 'Are you sure?'
       }, class:'btn btn-outline-primary m-1' %>
     </div>

     <div>
       <%= link_to 'comment', new_user_post_comment_path(post.user.id, post.id), class:'btn btn-outline-primary m-1'%>
     </div>
   </div>
 </div>
    <%= render 'partials/post', post: post %>
   
<% end %>

app/views/posts/new.html.erb
<br />
<section class='d-flex justify-content-center'>
    <div class='card w-75 border-success'>
      <div class='card-header d-flex justify-content-center header'>
        <h2 class='text-success'>Create post</h2>
      </div>

    <div class='card-body'>
      <%= form_with(model: [@user, @post], url:user_posts_path(current_user), method: :post) do |form| %>
        <div class="form-group">
        <%= form.label :title, hidden:true %>
        <%= form.text_field :title, required: true, placeholder:'Title', class:'form-control' %>
    
        <br />
        <%= form.label :content, hidden:true %>
        <%= form.text_area :content, required: true, placeholder: 'Content', class:'post_content' %>

        <br /> <br />
        <div class='d-flex justify-content-center'>
          <%= form.submit 'Create post', class: 'btn btn-outline-primary' %>
        </div>
        
      <% end %>
    </div>
    
  </div>
</section>

app/views/posts/show.html.erb
<br />
<section>
  <div class='d-flex justify-content-between'>
    <div>Post index: <%= @post.id%> </div>
    <div>
      <span>Likes: <%= @post.likes.count %></span>
      <span>Comments: <%= @post.comments_counter %></span>
    </div>
  </div>
  <br/>
<div>
  <div><%= @post.title %></div>
  (By: <%= @post.user.first_name %> <%= @post.user.last_name %> )
  <div>
    Content: <%= @post.content %>
  </div>
</div>

<br />
Comments:
<br />
<% @comments.each do |comment| %>
    <%= comment.comment %>
<% end %>
<br />

<%= form_with(model: [@user, @post, @like], local: true) do |form| %>
  <%= submit_tag "Like" %>
<% end %>

</section>

  
  

app/views/users/index.html.erb
<br />
<form class="form-inline my-2 my-lg-0 d-flex justify-content-end" action="<%= users_path %>" method="get">
  <input class="form-control mr-sm-2" type="search" name="search" placeholder="Search Users" aria-label="Search" value="<%= params[:search] %>">
  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>

<br />
<div class='container'>

  <% if params[:search].present? %>
    <% if @users.any? %>
      <% @users.each do |user| %>
        <div class='users'>
          <%= render 'partials/user', user: user %>
        </div> <br />
    <% end %>
  <% else %>
    <div class='users'>
      <p>No results found.</p>
    </div>
    <% end %>
  <% else %>
    <% @users.each do |user| %>
      <div class='users'>
        <%= render 'partials/user', user: user %>
      </div> <br />
    <% end %>
  <% end %>
  
</div>

app/views/users/show.html.erb
<section class='user_show'>
  <h2 class='d-flex justify-content-center bg-success'>User Profile</h2>

  <div class='p-2'>
    <div class='d-flex justify-content-between'>
      <div class="d-flex justify-content-center align-items-center profile_image_container">
        <% if @user.photo %>
          <%= @user.photo %>
        <% else %>
          <p>no photo!</p>
        <% end %>
      </div>
<% if @user.image? %>
  <%= image_tag @user.image.url %>
  <%else%>
  <p>noooo image</p>
<% end %>
      <div class='d-flex flex-column justify-content-around w-75'>
        <div>
          <%= @user.first_name %>
          <%= @user.last_name %>
        </div>
        <div class='d-flex justify-content-end w-100'>
          Posts: <%= @user.posts_counter %>
        </div>
      </div>
    </div>

    <hr class='d-flex justify-content-center w-50'/>
  
    <span>Contact</span>
    <div class='user_show_contact p-2'>
      <div class='d-flex'>
        <div class='w-50'> Phone: <%= @user.phone %> </div>
        <div class='w-50'> Email: <%= @user.email %> </div>
      </div>
      <div class='w-50'> Twitter: <%= @user.twitter %>  </div>
    </div>

    <br />
    <span>Bio</span>
    <div class='bio p-2'>
      <%= @user.bio %>
    </div>

    <br />
    <div class='d-flex justify-content-end'>Updated:  <%= @user.updated_at %> </div>
    <hr />
  </div>

  <h3> <%= @user.first_name %> <%= @user.last_name %>'s Articles</h3>
  <% if @user_posts.count > 5%>
    <% @user_posts.limit(5).each do |user_post| %>
      <%= render 'partials/post', post: user_post %>
    <% end %>
    <%= link_to 'more posts', user_posts_path(@user.id) %>
  <% else %>
    <% @user_posts.each do |user_post| %>
      <%= render 'partials/post', post: user_post %>
    <% end %>
  <% end %>  
</section>



 
  